### ISSUE TITLE
Awesome! Demo of completed project?

### ISSUE THREAD

**Issue by olddustysocksunderthecouch** [chidimo/React-Infinite-Scroll-and-Lazy-Loading#2]
Awesome article and project! Just a tip:

I think a lot more people would use/interact with your repo if you hosted a sample of the completed project somewhere (Github pages perhaps). Alternatively/additionally add a quick start guide on how to get the repo up and running locally.

**Comment by chidimo** [comment]
Thanks for the suggestion. It didn't come to mind.

I have done as you suggested.  I've deployed to Github pages and also added a quick start section to the readme.

Live preview <https://chidimo.github.io/React-Infinite-Scroll-and-Lazy-Loading/>

**Comment by chidimo** [comment]
Resolved
