### ISSUE TITLE
bug - scrollObserver makes first fetch to duplicate loading

### ISSUE THREAD

**Issue by originalkaratechop** [chidimo/React-Infinite-Scroll-and-Lazy-Loading#4]
I was following the tutorial and I've discovered that adding observer `const scrollObserver = useCallback(...` causes first fetched batch of images to be loaded twice. Lazy loading does not affect this.

I've subsribed a logger to changes of images array along with a logger in `imgReducer `to see what's happening
```
	case 'STACK_CARDS':
		console.log(state)
...
	useEffect(
		() => {console.log('hooks loading ', imgData.images.length)},
		[imgData.images.length]
	)
```

Normally after reaching the bottom fetching starts and we get `fetching: true` state. However on mount and render we get first time loaded `fetching: true` state and then same images are loaded again but with `fetching: false` state. All new images are loaded once with `fetching: true`

**Comment by chidimo** [comment]
I'm swamped with work right now. I could have investigated this a bit. But here's what I think is happening.

When the app loads, the div we're observing for intersection is already in view, so it triggers the API call. We could work around this using the intersectionObserver config or by giving the div more height so that it pushes the intersection we're observing downwards and out of view.

**Comment by originalkaratechop** [comment]
@chidimo 
I've increased `fetch()` limit to 30 to be sure that page is fully covered up to observing `<div/>` at the bottom. However all 30 images were duplicated. Adding `height` to the `<div/>` also had no effect. Probably thats because the `useEffect()` might be running on default on first render before it gets any subscription updated.

**upd:**
I've fixed that behaviour like this
1. moved both reducerds out of the `function App()`. Because it was adding additional `pageReducer` triggering

```
  const imgReducer = (state, action) => {
    switch (action.type) {
      case 'STACK_IMAGES':
        return { ...state, images: state.images.concat(action.images) }
      case 'FETCHING_IMAGES':
        return { ...state, fetching: action.fetching }
      default:
        return state;
    }
  }

  const pageReducer = (state, action) => {
    switch (action.type) {
      case 'ADVANCE_PAGE':
        return { ...state, page: state.page + 1 }
      default:
        return state;
    }
  }
function App() {
  const [pager, pagerDispatch] = useReducer(pageReducer, { page: 0 })
  const [imgData, imgDispatch] = useReducer(imgReducer, { images: [], fetching: true, })
```

2. since I could not find any fitting config of `intersectionObserver` I've modified  `useEffect()` of `cardDispatch` by adding `let initialRender = useRef(true)` along with new `if` condition for `customHooks.js` (it give warning in `useEffect()`)  like this:

```
//in app.js
	let initialRender = useRef(true)
	useFetch(pager, cardDispatch, initialRender);

//in custom hooks.js 
export const useFetch = (data, dispatch, initialRender) => {
	useEffect(
		() => {
			if (!initialRender.current) {
				dispatch({ type: 'FETCHING_IMAGES', fetching: true })
				fetch(`https://picsum.photos/v2/list?page=${data.page}&limit=2`)
					.then((data) => data.json())
					.then((images) => {
						dispatch({ type: 'STACK_IMAGES', images })
						dispatch({ type: 'FETCHING_IMAGES', fetching: false })
					})
					.catch((e) => {
						// handle error
						dispatch({ type: 'FETCHING_IMAGES', fetching: false })
						return e
					})
			} else {
				initialRender.current = false
			}
		},
		[dispatch,data.page]
	)
}

```

or if purely in `app.js` like this

```
let initialRender = useRef(true)
export const useFetch = (data, dispatch) => {
	useEffect(
		() => {
			if (!initialRender.current) {
				dispatch({ type: 'FETCHING_IMAGES', fetching: true })
				fetch(`https://picsum.photos/v2/list?page=${data.page}&limit=2`)
					.then((data) => data.json())
					.then((images) => {
						dispatch({ type: 'STACK_IMAGES', images })
						dispatch({ type: 'FETCHING_IMAGES', fetching: false })
					})
					.catch((e) => {
						// handle error
						dispatch({ type: 'FETCHING_IMAGES', fetching: false })
						return e
					})
			} else {
				initialRender.current = false
			}
		},
		[dispatch,data.page]
	)
}
```

**Comment by chidimo** [comment]
Great thoughts.

I'll find time to look at this in more detail.
