### ISSUE TITLE
can I translate you article into Chinese?

### ISSUE THREAD

**Issue by xkx9431** [chidimo/React-Infinite-Scroll-and-Lazy-Loading#5]
just find your article is excellent to study the hooks, the lazy loading or infinite scroll, I want translate this  into Chinese, and I wonder  if you permit me do that,  I will preserve and declare you the awesome author, and the link for your git repos, So if possible ,just let me translate, and I will  show you the after result later, thanks.

**Comment by xkx9431** [comment]
sorry not have the twitter, just post here, and close it.

**Comment by chidimo** [comment]
Hello, thanks for reaching out.

That would be lovely. Let me get back to you on that tomorrow. You can send me an email on orjichidi95@gmail.com.

**Comment by chidimo** [comment]
Hey.
You can go ahead and translate it.

Just be sure to add a link to the original article.

Cheers.
Chidi

**Comment by xkx9431** [comment]
> Hey.
> You can go ahead and translate it.
> 
> Just be sure to add a link to the original article.
> 
> Cheers.
> Chidi

@chidimo  thank you a lot, and I will give the original link.
